name: Build and Push Images

on:
  release:
    types: [published]

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dropletbot
          password: ${{ secrets.botDockerHubPassword }}
      - name: Build and push CPU image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.cpu
          tags: instill/triton-conda-env:${{ github.ref_name }}-cpu
          cache-from: type=registry,ref=triton-conda-env:buildcache-cpu
          cache-to: type=registry,ref=triton-conda-env:buildcache-cpu,mode=max
      - name: Build and push GPU image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.gpu
          tags: instill/triton-conda-env:latest,instill/triton-conda-env:${{ github.ref_name }}-gpu
          cache-from: type=registry,ref=triton-conda-env:buildcache
          cache-to: type=registry,ref=triton-conda-env:buildcache,mode=max
