name: Build and Push Images

on:
  release:
    types: [published]

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dropletbot
          password: ${{ secrets.botDockerHubPassword }}
      - name: Set up Docker Buildx for CPU image
        uses: docker/setup-buildx-action@v1
        id: builder-cpu
      - name: Set up Docker Buildx for GPU image
        uses: docker/setup-buildx-action@v1
        id: builder-gpu
      - name: Build and push CPU image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder-cpu.outputs.name }}
          push: true
          file: Dockerfile.cpu
          tags: instill/triton-conda-env:${{ github.ref_name }}-cpu
          build-args: TRITON_PYTHON_MODEL_VERSION=${{ github.ref_name }}
          cache-from: type=registry,ref=instill/triton-conda-env:buildcache-cpu
          cache-to: type=registry,ref=instill/triton-conda-env:buildcache-cpu,mode=max
      - name: Build and push GPU image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder-gpu.outputs.name }}
          push: true
          file: Dockerfile.gpu
          tags: instill/triton-conda-env:latest,instill/triton-conda-env:${{ github.ref_name }}-gpu
          build-args: TRITON_PYTHON_MODEL_VERSION=${{ github.ref_name }}
          cache-from: type=registry,ref=instill/triton-conda-env:buildcache-gpu
          cache-to: type=registry,ref=instill/triton-conda-env:buildcache-gpu,mode=max
